apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - name: configmap
          mountPath: /usr/share/nginx/html/
          readOnly: true
      volumes:
        - name: configmap
          configMap:
            name: test-config
            items:
            - key: index
              path: "index.html"
